server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_PROD}/${DB_NAME_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}

  kafka:
    bootstrap-servers: ${KAFKA_URL_PROD}
    listener:
      auto-startup: true

  jpa:
    hibernate:
      ddl-auto: validate