server:
  port: 8080

snowflake:
  node-id: 201

spring:
  application:
    name: book-loan-service
  
  profiles:
    active: local

  # .env 파일에서 환경 변수를 가져오는 설정 (공통으로 사용)
  config:
    import: optional:file:.env[.properties]

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # 추후 변경
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: loan-service-bookinfo-replica
      auto-offset-reset: earliest
    listener:
      auto-startup: false # 기본적으로 리스너를 자동 시작하지 않게 일단 해뒀음. 추후 변경




# 커스텀 설정
app:
  kafka:
    source-token: book-loan

    # commands
    topic-member-check: member.check
    topic-inventory-reserve: inventory.reserve
    topic-point-charge: point.charge
    topic-point-refund: point.refund
    topic-shipping-schedule: shipping.schedule
    topic-inventory-release: inventory.release

    # single reply channel
    topic-saga-replies: loan.saga.replies

    # catalog
    topic-catalog-changed: book-catalog.changed

    # groups
    group-saga-replies: bookloan-saga-replies
    group-catalog-replica: bookloan-category-changed-replica

  saga:
    timeout:
      batch-size: 50
      lease-sec: 15
    overall-timeout: 3m
    default-step-timeout: 30s
    steps:
      member-checking: 10s
      inventory-reserving: 20s
      point-charging: 15s
      shipping-scheduling: 30s
      shipping-accepted: 10m
