server.port: 9000

spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
    listener:
      auto-startup: false




kafka:
  topics:
    category-changed: book-catalog-changed
  group:
    bookloan:
      category-replica: bookloan-category-changed-replica
