spring:
  datasource:

    url: jdbc:mysql://localhost:13306/appdb?useSSL=false...

    username: ${MYSQL_LOAN_USER}
    password: ${MYSQL_LOAN_PASSWORD}

  kafka:

    bootstrap-servers: kafka:9092
    listener:
      auto-startup: true

logging:
  level:
    org.hibernate.SQL: debug