spring:
  datasource:
    url: jdbc:mysql://localhost:13307/catalogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${MYSQL_CATALOG_USER}
    password: ${MYSQL_CATALOG_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092