spring:
  datasource:
    url: jdbc:mysql://localhost:13307/catalogdb?sslMode=DISABLED&rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_CATALOG_USER}
    password: ${MYSQL_CATALOG_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 500
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql


  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.tool.schema: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

aladin:
  batch:
    enabled: false

outbox:
  relay:
    enabled: false        # ← 꺼둠
    fixed-delay-ms: 60000 # (선택) 주기 설정